language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

# install os dependencies
addons:
  apt:
    packages:
      - proj-bin
      - libhdf5-serial-dev
      - libproj-dev
      - libgeos-dev
      - libspatialindex-dev

# Try GDAL stuff
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgdal-dev
  - sudo export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - sudo export C_INCLUDE_PATH=/usr/include/gdal


# install python dependencies
install:
  - pip install cython
  - pip install .
  - pip install coveralls

# command to run tests and coverage
script:
  - nosetests --with-doctest --with-coverage -c nose.cfg

after_success:
  - coveralls
