language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

# install os dependencies
addons:
  apt:
    packages:
      - proj-bin
      - libhdf5-serial-dev
      - libproj-dev
      - libgeos-dev
      - libspatialindex-dev

# install python dependencies
install:
  - pip install cython
  - pip install .
  - pip install coveralls

# command to run tests and coverage
script:
  - coverage run --rcfile=.coveragerc --source deflex -m py.test
  - coverage report
  - 
after_success:
  - coveralls
