language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

# install os dependencies
addons:
  apt:
    packages:
      - proj-bin
      - libhdf5-serial-dev
      - libproj-dev
      - libgeos-dev
      - libspatialindex-dev
      - libgdal-dev
      - gdal-bin

# install python dependencies
install:
  - pip install cython
  - pip install .
  - pip install coveralls

# command to run tests and coverage
script:
  - nosetests --with-doctest --with-coverage -c nose.cfg

after_success:
  - coveralls
